FROM node:19.7
ENV NEW_RELIC_NO_CONFIG_FILE=true
ENV NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
ENV NEW_RELIC_LOG=stdout
WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
EXPOSE 8000

CMD ["npm", "start"]

